// Quellenverzeichnis. Im Text wird mit [[schluessel]] zitiert; die Nummern
// vergibt build.js automatisch in der Reihenfolge des ersten Auftretens.
module.exports = {
  mann2007: 'Mann T, Tomiyama AJ, Westling E, et al. Medicare’s search for effective obesity treatments: diets are not the answer. <i>Am Psychol.</i> 2007;62(3):220–233.',
  sumithran2011: 'Sumithran P, Prendergast LA, Delbridge E, et al. Long-term persistence of hormonal adaptations to weight loss. <i>N Engl J Med.</i> 2011;365(17):1597–1604.',
  fothergill2016: 'Fothergill E, Guo J, Howard L, et al. Persistent metabolic adaptation 6 years after “The Biggest Loser” competition. <i>Obesity.</i> 2016;24(8):1612–1619.',
  hill2009: 'Hill JO. Can a small-changes approach help address the obesity epidemic? A report of the Joint Task Force of the American Society for Nutrition, Institute of Food Technologists, and International Food Information Council. <i>Am J Clin Nutr.</i> 2009;89(2):477–484.',
  hall2011: 'Hall KD, Sacks G, Chandramohan D, et al. Quantification of the effect of energy imbalance on bodyweight. <i>Lancet.</i> 2011;378(9793):826–837.',
  wing2005: 'Wing RR, Phelan S. Long-term weight loss maintenance. <i>Am J Clin Nutr.</i> 2005;82(1 Suppl):222S–225S.',
  thorogood2011: 'Thorogood A, Mottillo S, Shimony A, et al. Isolated aerobic exercise and weight loss: a systematic review and meta-analysis of randomized controlled trials. <i>Am J Med.</i> 2011;124(8):747–755.',
  herman1975: 'Herman CP, Mack D. Restrained and unrestrained eating. <i>J Pers.</i> 1975;43(4):647–660.',
  polivy1985: 'Polivy J, Herman CP. Dieting and binging: a causal analysis. <i>Am Psychol.</i> 1985;40(2):193–201.',
  wood2002: 'Wood W, Quinn JM, Kashy DA. Habits in everyday life: thought, emotion, and action. <i>J Pers Soc Psychol.</i> 2002;83(6):1281–1297.',
  lally2010: 'Lally P, van Jaarsveld CHM, Potts HWW, Wardle J. How are habits formed: modelling habit formation in the real world. <i>Eur J Soc Psychol.</i> 2010;40(6):998–1009.',
  gardner2012: 'Gardner B, Lally P, Wardle J. Making health habitual: the psychology of “habit-formation” and general practice. <i>Br J Gen Pract.</i> 2012;62(605):664–666.',
  lally2008: 'Lally P, Chipperfield A, Wardle J. Healthy habits: efficacy of simple advice on weight control based on a habit-formation model. <i>Int J Obes.</i> 2008;32(4):700–707.',
  beeken2017: 'Beeken RJ, Leurent B, Vickerstaff V, et al. A brief intervention for weight control based on habit-formation theory delivered through primary care: results from a randomised controlled trial. <i>Int J Obes.</i> 2017;41(2):246–254.',
  gollwitzer2006: 'Gollwitzer PM, Sheeran P. Implementation intentions and goal achievement: a meta-analysis of effects and processes. <i>Adv Exp Soc Psychol.</i> 2006;38:69–119.',
  malik2006: 'Malik VS, Schulze MB, Hu FB. Intake of sugar-sweetened beverages and weight gain: a systematic review. <i>Am J Clin Nutr.</i> 2006;84(2):274–288.',
  dimeglio2000: 'DiMeglio DP, Mattes RD. Liquid versus solid carbohydrate: effects on food intake and body weight. <i>Int J Obes Relat Metab Disord.</i> 2000;24(6):794–800.',
  temorenga2013: 'Te Morenga L, Mallard S, Mann J. Dietary sugars and body weight: systematic review and meta-analyses of randomised controlled trials and cohort studies. <i>BMJ.</i> 2013;346:e7492.',
  deruyter2012: 'de Ruyter JC, Olthof MR, Seidell JC, Katan MB. A trial of sugar-free or sugar-sweetened beverages and body weight in children. <i>N Engl J Med.</i> 2012;367(15):1397–1406.',
  ebbeling2012: 'Ebbeling CB, Feldman HA, Chomitz VR, et al. A randomized trial of sugar-sweetened beverages and adolescent body weight. <i>N Engl J Med.</i> 2012;367(15):1407–1416.',
  who2015: 'World Health Organization. <i>Guideline: Sugars intake for adults and children.</i> Genf: WHO; 2015.',
  dge2018: 'Ernst JB, Arens-Azevêdo U, Bitzer B, et al. <i>Quantitative Empfehlung zur Zuckerzufuhr in Deutschland.</i> Konsensuspapier der Deutschen Adipositas-Gesellschaft (DAG), der Deutschen Diabetes Gesellschaft (DDG) und der Deutschen Gesellschaft für Ernährung (DGE). Bonn; 2018.',
  mcglynn2022: 'McGlynn ND, Khan TA, Wang L, et al. Association of low- and no-calorie sweetened beverages as a replacement for sugar-sweetened beverages with body weight and cardiometabolic risk factors: a systematic review and meta-analysis. <i>JAMA Netw Open.</i> 2022;5(3):e222092.',
  rogers2016: 'Rogers PJ, Hogenkamp PS, de Graaf C, et al. Does low-energy sweetener consumption affect energy intake and body weight? A systematic review, including meta-analyses, of the evidence from human and animal studies. <i>Int J Obes.</i> 2016;40(3):381–394.',
  peters2014: 'Peters JC, Wyatt HR, Foster GD, et al. The effects of water and non-nutritive sweetened beverages on weight loss during a 12-week weight loss treatment program. <i>Obesity.</i> 2014;22(6):1415–1421.',
  who2023: 'World Health Organization. <i>Use of non-sugar sweeteners: WHO guideline.</i> Genf: WHO; 2023.',
  riboli2023: 'Riboli E, Beland FA, Lachenmeier DW, et al. Carcinogenicity of aspartame, methyleugenol, and isoeugenol. <i>Lancet Oncol.</i> 2023;24(8):848–850.',
  who2023b: 'World Health Organization, International Agency for Research on Cancer, Joint FAO/WHO Expert Committee on Food Additives. <i>Aspartame hazard and risk assessment results released.</i> Pressemitteilung, Genf, 14. Juli 2023.',
  witkowski2023: 'Witkowski M, Nemet I, Alamri H, et al. The artificial sweetener erythritol and cardiovascular event risk. <i>Nat Med.</i> 2023;29(3):710–718.',
  wise2016: 'Wise PM, Nattress L, Flammer LJ, Beauchamp GK. Reduced dietary intake of simple sugars alters perceived sweet taste intensity but not perceived pleasantness. <i>Am J Clin Nutr.</i> 2016;103(1):50–60.',
  stewart2012: 'Stewart JE, Keast RSJ. Recent fat intake modulates fat taste sensitivity in lean and overweight subjects. <i>Int J Obes.</i> 2012;36(6):834–842.',
  eu1924: 'Verordnung (EG) Nr. 1924/2006 des Europäischen Parlaments und des Rates vom 20. Dezember 2006 über nährwert- und gesundheitsbezogene Angaben über Lebensmittel. <i>ABl. EU</i> L 404 vom 30.12.2006.',
  provencher2009: 'Provencher V, Polivy J, Herman CP. Perceived healthiness of food. If it’s healthy, you can have more! <i>Appetite.</i> 2009;52(2):340–344.',
  hall2019: 'Hall KD, Ayuketah A, Brychta R, et al. Ultra-processed diets cause excess calorie intake and weight gain: an inpatient randomized controlled trial of ad libitum food intake. <i>Cell Metab.</i> 2019;30(1):67–77.',
  kavanagh2005: 'Kavanagh DJ, Andrade J, May J. Imaginary relish and exquisite torture: the elaborated intrusion theory of desire. <i>Psychol Rev.</i> 2005;112(2):446–467.',
  skorka2014: 'Skorka-Brown J, Andrade J, May J. Playing “Tetris” reduces the strength, frequency and vividness of naturally occurring cravings. <i>Appetite.</i> 2014;76:161–165.',
  skorka2015: 'Skorka-Brown J, Andrade J, Whalley B, May J. Playing Tetris decreases drug and other cravings in real world settings. <i>Addict Behav.</i> 2015;51:165–170.',
  rolls2004: 'Rolls BJ, Roe LS, Meengs JS. Salad and satiety: energy density and portion size of a first-course salad affect energy intake at lunch. <i>J Am Diet Assoc.</i> 2004;104(10):1570–1576.',
  ellomartin2007: 'Ello-Martin JA, Roe LS, Ledikwe JH, Beach AM, Rolls BJ. Dietary energy density in the treatment of obesity: a year-long trial comparing 2 weight-loss diets. <i>Am J Clin Nutr.</i> 2007;85(6):1465–1477.',
  flood2007: 'Flood JE, Rolls BJ. Soup preloads in a variety of forms reduce meal energy intake. <i>Appetite.</i> 2007;49(3):626–634.',
  dennis2010: 'Dennis EA, Dengo AL, Comber DL, et al. Water consumption increases weight loss during a hypocaloric diet intervention in middle-aged and older adults. <i>Obesity.</i> 2010;18(2):300–307.',
  parretti2015: 'Parretti HM, Aveyard P, Blannin A, et al. Efficacy of water preloading before main meals as a strategy for weight loss in primary care patients with obesity: RCT. <i>Obesity.</i> 2015;23(9):1785–1791.',
  weigle2005: 'Weigle DS, Breen PA, Matthys CC, et al. A high-protein diet induces sustained reductions in appetite, ad libitum caloric intake, and body weight despite compensatory changes in diurnal plasma leptin and ghrelin concentrations. <i>Am J Clin Nutr.</i> 2005;82(1):41–48.',
  hollands2015: 'Hollands GJ, Shemilt I, Marteau TM, et al. Portion, package or tableware size for changing selection and consumption of food, alcohol and tobacco. <i>Cochrane Database Syst Rev.</i> 2015;(9):CD011045.',
  bucher2016: 'Bucher T, Collins C, Rollo ME, et al. Nudging consumers towards healthier choices: a systematic review of positional influences on food choice. <i>Br J Nutr.</i> 2016;115(12):2252–2263.',
  oldhamcooper2011: 'Oldham-Cooper RE, Hardman CA, Nicoll CE, Rogers PJ, Brunstrom JM. Playing a computer game during lunch affects fullness, memory for lunch, and later snack intake. <i>Am J Clin Nutr.</i> 2011;93(2):308–313.',
  robinson2013: 'Robinson E, Aveyard P, Daley A, et al. Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating. <i>Am J Clin Nutr.</i> 2013;97(4):728–742.',
  ohkuma2015: 'Ohkuma T, Hirakawa Y, Nakamura U, et al. Association between eating rate and obesity: a systematic review and meta-analysis. <i>Int J Obes.</i> 2015;39(11):1589–1596.',
  spiegel2004: 'Spiegel K, Tasali E, Penev P, Van Cauter E. Brief communication: sleep curtailment in healthy young men is associated with decreased leptin levels, elevated ghrelin levels, and increased hunger and appetite. <i>Ann Intern Med.</i> 2004;141(11):846–850.',
  tasali2022: 'Tasali E, Wroblewski K, Kahn E, Kilkus J, Schoeller DA. Effect of sleep extension on objectively assessed energy intake among adults with overweight in real-life settings: a randomized clinical trial. <i>JAMA Intern Med.</i> 2022;182(4):365–374.',
  epel2001: 'Epel E, Lapidus R, McEwen B, Brownell K. Stress may add bite to appetite in women: a laboratory study of stress-induced cortisol and eating behavior. <i>Psychoneuroendocrinology.</i> 2001;26(1):37–49.',
  torres2007: 'Torres SJ, Nowson CA. Relationship between stress, eating behavior, and obesity. <i>Nutrition.</i> 2007;23(11–12):887–894.',
  adam2007: 'Adam TC, Epel ES. Stress, eating and the reward system. <i>Physiol Behav.</i> 2007;91(4):449–458.',
  yau2013: 'Yau YHC, Potenza MN. Stress and eating behaviors. <i>Minerva Endocrinol.</i> 2013;38(3):255–267.',
  balban2023: 'Balban MY, Neri E, Kogon MM, et al. Brief structured respiration practices enhance mood and reduce physiological arousal. <i>Cell Rep Med.</i> 2023;4(1):100895.',
  luppino2010: 'Luppino FS, de Wit LM, Bouvy PF, et al. Overweight, obesity, and depression: a systematic review and meta-analysis of longitudinal studies. <i>Arch Gen Psychiatry.</i> 2010;67(3):220–229.',
  konttinen2010: 'Konttinen H, Männistö S, Sarlio-Lähteenkorva S, Silventoinen K, Haukkala A. Emotional eating, depressive symptoms and self-reported food consumption. A population-based study. <i>Appetite.</i> 2010;54(3):473–479.',
  jacka2017: 'Jacka FN, O’Neil A, Opie R, et al. A randomised controlled trial of dietary improvement for adults with major depression (the “SMILES” trial). <i>BMC Med.</i> 2017;15(1):23.',
  cuijpers2007: 'Cuijpers P, van Straten A, Warmerdam L. Behavioral activation treatments of depression: a meta-analysis. <i>Clin Psychol Rev.</i> 2007;27(3):318–326.',
  adams2007: 'Adams CE, Leary MR. Promoting self-compassionate attitudes toward eating among restrictive and guilty eaters. <i>J Soc Clin Psychol.</i> 2007;26(10):1120–1144.',
  serretti2010: 'Serretti A, Mandelli L. Antidepressants and body weight: a comprehensive review and meta-analysis. <i>J Clin Psychiatry.</i> 2010;71(10):1259–1272.',
};
